### ISSUE TITLE
Out of global stack

### ISSUE THREAD

**Issue by rzach** [rzach/multlog#12]
ERROR: -g lgc2tex('shramko-wansing.lgc','shramko-wansing.sty','shramko-wansing.cfg'), halt.: Out of global stack

Any way around this? This happens for the quantifier in the 16-valued bilattice.

**Comment by gsalzer** [comment]
In the last commit, I have modified `lgc2...` to forward any additional parameters to Prolog. Try to increase the stack size using
```
lgc2tex shramko-wansing  --stack-limit=32g
```
The default on 32bit architectures is 512M and on 64bit architectures 1g.

The underlying problem is that the complexity of some algorithms is high (regarding time and stack size), depending on the number of truth values. For inf/sup-defined operators and quantifiers, the complexity should be lower, though.

**Comment by gsalzer** [comment]
Seems to be a different problem. Same error with lots of stack. In fact, swipl doesn't seem to use much memory when running into this error. Still checking ...

**Comment by gsalzer** [comment]
@rzach It seems we can close this issue: I just tried it on a machine with some memory, and the command
```console
lgc2tex shramko-wansing.lgc --stack-limit=100G
```
terminated after 5 hours successfully. So it just seems to be a matter of resources.

**Comment by rzach** [comment]
Ok!
